# Note: topics should be as same as the file name of the topic in the _topics directory
#   when slugified; when all non-alphanumeric characters are replaced by a hyphen.
jekyll:
  topics:
    - "Static Site Generators"
    - "Web Development Technologies"
  similar-technologies:
    - "Hugo"
    - "Gatsby"
    - "MkDocs"
    - "VuePress"
    - "Next.js"
  related-technologies:
    - "Ruby"
    - "Liquid"
    - "Github Pages"
    - "Kramdown"
    - "Rouge"
  important:
    - name: "Jekyll Guide"
      url: "https://github.com/shadhini/jekyll-tryouts/blob/main/jekyll-guide.md"
    - name: Jekyll Quick Reference Guide
      url: "https://github.com/shadhini/jekyll-tryouts/blob/main/jekyll-quick-reference-guide.md"
    - name: "Jekyll Tryouts Demo Website"
      url: "https://shadhini.github.io/jekyll-tryouts/"
    - name: Jekyll Reusable Templates in my Jekyll Tryouts Repo
      url: "https://github.com/shadhini/jekyll-tryouts/blob/main/jekyll-reusable-templates.md"
    - name: "Jekyll Template for Technology Catalog"
      url: "https://github.com/shadhini/daily-dev/releases/tag/tech-catalog-jekyll-template-v0.2"
json:
  topics:
    - "Data Formats"
  similar-technologies:
    - "YAML"
  related-technologies:
    - "JSON Schema"
yaml:
  topics:
    - "Data Formats"
  similar-technologies:
    - "JSON"
json-schema:
  topics:
    - "Data Validation"
  related-technologies:
    - "JSON"
github-copilot:
  topics:
    - "Dev Tools"
    - "MCP"
  important:
    - name: "Github Copilot CLI: Configurations"
      url: "https://github.com/shadhini/daily-dev/blob/main/github-copilot-cli/configurations.md"
    - name: "Github Copilot CLI: Commands"
      url: "https://github.com/shadhini/daily-dev/blob/main/github-copilot-cli/commands.md"
intellij-idea:
  topics:
    - "Dev Tools"
  important:
    - name: "IntelliJ IDEA: Debugging"
      url: "https://github.com/shadhini/daily-dev/blob/main/IDE-support/IntelliJIDEA/debugging.md"
    - name: "Github Copilot CLI: Version Control"
      url: "https://github.com/shadhini/daily-dev/blob/main/IDE-support/IntelliJIDEA/version-control.md"
    - name: "IntelliJ IDEA: Shortcuts"
      url: "https://github.com/shadhini/daily-dev/blob/main/IDE-support/IntelliJIDEA/shortcuts.md"
maven:
  topics:
    - "Dev Tools"
  important:
    - name: "Maven: Commands"
      url: "https://github.com/shadhini/daily-dev/blob/main/build-tools/maven/commands.md"
spring:
