remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one

title: DailyDev
description: A concise collection of essential commands, coding snippets, handy tips and technology catalog for daily development.

show_downloads: true
google_analytics: ""
